pspdev/psp-packages

sdl2/PSPBUILD
This incorporates the change made in https://github.com/pspdev/SDL/pull/1
=> Fix sdl2 applications failing to build at linking stage

pixman/PSPBUILD
Seems that newer versions of binutils make this test fail somehow.
(Even though I cannot reproduce this locally with either toolchain version!)
=> Disable loongson manually since autodetect seems to fail for allegrex

zlib/PSPBUILD, zlib/cmake.patch
Building two of them seems to cause some race conditions on multithread builds (particularly on the CI)
Tested locally :)
=> Patch zlib cmake and ensure we only build one library (static)

.github/workflows/build.yml
This is currently causing issues randomly. We have no system in place which guarantees that all dependencies are available for all artifacts in the build_depends stage of the build process. With this change, this should no longer matter. This solution works, because the packages which have this issue are never needed to build the current package.
=> Don't check dependencies when installing artifacts

libconfuse/PSPBUILD
While at it, bump rel number to ensure we get a proper build and no
conflicts
=> Use libconfuse package release instead of git

build.sh, parse_pspbuild.sh
This allows building and installing all packages manually. It respects dependency ordering.
This is not used at all as it is, but will send another PR to optionally use it if the user wants it that way.
=> Add a package build script.

CONTRIBUTING.md
It needs more improvements. It could use some instructions. In the meantime, this was the only information which was wrong.
=> Improve versioning info for version control systems

libxmp/PSPBUILD
This fixes the occasional failures we are seeing.
=> Make libxmp only build the static library

pixman/PSPBUILD
Fixes the non-standard directory naming. Also removes the usage of
autogen.sh script, which seems to cause some issues on mismatching
autoreconf versions.
Most distros seem to use the freedesktop release archive too.
=> Use pixman's release package instead of git

.github/workflows/build.yml
Without this change it will not be possible to use pkg-config in build scripts, since pkg-config is no longer bundled and the wrapper script uses it.
=> Make sure pkg-config is available

sdl2/PSPBUILD
Upstream SDL2 has been improved to the point where it is much better than the PSPDEV port. There are still some rendering issues in some rare cases, but those are also found in our old port. This is still the in development version, but there is no release with our changes yet.
=> Use upstream SDL2

sdl2-ttf/PSPBUILD
This is the new release version 2.0.18 which has support for CMake, but it's not really quite official yet. It works well for us, though. I did needed to delete one line from the CMakeLists.txt file, but otherwise it builds and works.
=> Upgrade to new SDL2_ttf version

sdl2/PSPBUILD
3 bugs were fixed upstream for which there is no release yet:
- RenderCopyEx wasn't working (https://github.com/libsdl-org/SDL/pull/5335)
- RenderDrawRect was only drawing the top sides (https://github.com/libsdl-org/SDL/pull/5341)
- Streaming textures were being swizzled, causing rendering issues when updating them (https://github.com/libsdl-org/SDL/commit/66ee79bd68335b9725fd94defc3e5ac5ff3c4249)
I think these fixes are important enough to not wait for the next
release.
=> Use latest upstream commit for sdl2

sqlite/PSPBUILD, sqlite/sqlite-3.7.4-PSP.patch
The tarball on the sqlite website was constantly changing, which is
totally unacceptable. The tag on the github should not change. I had to
adjust the patch a little bit to work with the next version, though. I
hope it works like expected, but I don't have an application I can test
this with.
=> Update sqlite to 3.7.4 with different mirror

openal/PSPBUILD
This re-adds OpenAL support, which we used to have before the change to psp-packages.
=> Add openal-soft

freetype2/PSPBUILD, libpng/PSPBUILD, sdl2-ttf/PSPBUILD, sdl2/PSPBUILD, zlib/PSPBUILD
This uses a commit on git, but it does build. Now when using ``psp-pkg-config --libs SDL2_ttf`` it will return freetype2 as well. This makes it so all dependencies are returned by it.
=> Fix PC file in sdl2-ttf and remove workaround

bzip2/PSPBUILD, jpeg/PSPBUILD, zziplib/PSPBUILD
This fixes a few things with some packages.
bzip2 was broken for a while (the latest github release is missing the bzlib2 library), weird nobody noticed!
=> Fix bzip2 and other minor improvements

sdl2-mixer/PSPBUILD
I've tested this and it works. ogg, wav and xmp. Xmp is new. Note to self, make sure to update the example on pspdev.github.io once this is merged.
=> Update sdl2-mixer to latest version

sdl2-image/PSPBUILD
This was required because we want pkg-config to work and the latest stable does not support pkg-config. I still need to give this a quick test.
=> Update SDL2_image to development version

eigen3/PSPBUILD
Eigen3 is an awesome C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
It is fully inline so there should not be any static or shared libraries required to link.
I would love to know how you would go about linking this one in a cmakelists.txt :D
=> Add Eigen3

polarssl/PSPBUILD
This PR builds polarssl v1.3.9
note: I know that polarSSL has been replaced by mbedTLS, but I still use polarSSL for some projects (mostly for the hashing and crypto implementations).
=> Add polarSSL

sdl2-image/PSPBUILD, sdl2-image/pkg-config-fix.patch, sdl2-mixer/PSPBUILD, sdl2-mixer/pkg-config-fix.patch, sdl2-ttf/PSPBUILD, sdl2-ttf/pkg-config-fix.patch, sdl2/PSPBUILD, sdl2/pkg-config-fix.patch
This also cleans up the PSPBUILD files a lot. I made patches instead of offering versions that do not exist. These will probably be the final packages for sdl2.
=> Update sdl2 and all helper libraries

.github/workflows/build.yml
Do not merge until this one has been merged: https://github.com/pspdev/pspsdk/pull/137
After this change, building the packages should be faster and not put strain on the alpine linux servers.
=> Do not install dependencies

libun7zip/PSPBUILD
Compiled library should be `libun7zip.a` but it was installed as `psp-libun7zip.a`
This PR fixes the installation file name of the un7zip compiled library.
=> Fix un7zip library file name

libxmp-lite/PSPBUILD, sdl2-mixer/PSPBUILD, sdl2-mixer/libxmp-lite-fix.patch
Since libmikmod support was removed from SDL2_mixer, I was linking to libxmp instead. Issue is, libxmp uses the GPL license, which is a big problem for software using it. This changes this to use libxmp-lite, which uses the MIT license, resolving the issue.
=> Fix sdl2 license issue

sdl2-mixer/PSPBUILD
This uses dr_mp3, which is bundled with the SDL2_mixer source code. It's actually faster than libogg.
=> Build SDL2_mixer with MP3 support

openal/PSPBUILD
It seems the tar.gz we use is not around anymore.
=> Fix OpenAL build

enet/PSPBUILD
Currently, headers are installed under `/usr/local/pspdev/psp/include/include/enet/`, and should be under `/usr/local/pspdev/psp/include/enet/`.
This is a simple fix, and it shouldn't be needed after the next version of enet is released (https://github.com/lsalzman/enet/pull/82 got merged, so the headers will be installed with `make install`).
=> enet: fix header installation path

.github/workflows/build.yml
Right now we get a lot of warnings that we should update our actions because they use an old node version. This should fix that.
=> Resolve deprecation warnings in GitHub Actions

install-latest.sh
This can be tested like this:
```
docker build --build-arg "BASE_DOCKER_IMAGE=ghcr.io/pspdev/pspsdk:latest" --build-arg "PACKAGES_REPO=pspdev/psp-packages" -t test .
```
=> Fix error in install-latest.sh script

create-matrix.js, harfbuzz/PSPBUILD, harfbuzz/fix-cmake.patch, sdl2-ttf/PSPBUILD
Again, I haven't yet tested if it works, so I am creating this PR as a draft. Just want to know if anything should be changed.
=> Add harfbuzz library

sdl/PSPBUILD
Don't warn on incompatible pointers on SDL1.2 for now
We could potentially backport the changes from the SDL1.2 repo, I am not sure if the SDL team would be willing to add our PSP Repo back to 1.2 sources, I will check with them
=> Don't warn on incompatible pointer types

mbedtls/PSPBUILD, mbedtls/mbedtls-2.16.6-PSP.patch
Not a functional change, just simplifying existing patch since sockaddr_storage is now supported, thus doesn't need to be patched out anymore.
Patch went from 218 lines to 182.
=> simplified patch for mbedtls

sdl2/PSPBUILD
Because SDL2 and SDL2main were listed twice in the libraries returned by psp-pkgconf, the psp-fixup-imports command was messing with the order of the SDL2 and SDL2main imports, causing SDL2main to not work. I got a patch merged upstream that fixes this, but there isn't a fixed release available yet, so I decided to just download the patch file from the PR.
=> SDL2: Fix SDL2main not working after running psp-fixup-imports

tremor/PSPBUILD, tremor/platform-allegrex.patch
The only package that was not moved from psp-ports to psp-packages. Should be faster than vorbis and can be used as a drop-in replacement.
I tried to find the commit that the fork in psp-ports was based on, and extract the patch (turns out it's just adding 4 lines to configure script).
=> Add tremor from psp-ports

tremor/PSPBUILD, tremor/platform-allegrex.patch
There has been some development of this library since 2007 when it was ported to PSP. Most notably: using external libogg instead of the bundled one and support for pkgconfig. The master branch however doesn't play nice with modern autotools, but there is a fork [sezero/tremor](https://github.com/sezero/tremor/) with fixes.
=> Update tremor to the latest source with modern patches

openal/PSPBUILD
The project recently switched to GitHub releases, so let's use them.
The correct license is LGPL-2.0 (GNU Library General Public License, Version 2) with parts being licensed under the 3-Clause BSD. From the next release, PFFFT library will also be bundled with its own license.
=> OpenAL Soft update

harfbuzz/PSPBUILD, harfbuzz/fix-cmake.patch
Just today I looked at how VITA community cooks their harfbuzz, so I copied the approach described in https://github.com/vitasdk/packages/issues/300, and it works really well: got SDL2-ttf sample (in C) built linking to harfbuzz, but not stdc++. Previously, I only built Jokr (written in C++) with it, so linking to stdc++ didn't bother me that much.
=> Update harfbuzz and patch out stdc++ dependency

sdl2-image/PSPBUILD, sdl2-mixer/PSPBUILD, sdl2-net/PSPBUILD
fix for the CI error:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.6.3.tar.gz
Aborting...
Error: Process completed with exit code 1.
```
=> update sources SDL2_(image, net, mixer)

.github/workflows/build.yml
The system with releases we use right now doesn't work so well. While we are releasing there is a chance that you might not get your package and we have over 300 releases on this repo of which only the last one is ever used.
This PR makes it so we upload to GitHub Pages instead, which then hosts our repo for us. It does not leave old stuff lying around, it just deploys the artifact we give it. We could also later expand it to have a web page in front like @tpimh suggested.
This does require a change in the psp-pacman repo and a rebuild from there after merging. Merging this won't cause errors directly, but the releases will stop being updated. It is possible that in the settings of this repo, GitHub Pages will need to be set to "GitHub Action" before the pipeline goes through.
If you want …
=> Use GitHub pages for hosting

README.md
This was still missing from the README.
=> Add info on pacman repository hosting

sdl2/PSPBUILD
This was added in PRs, but there is no release for it yet, so I'm using the patch files from the PRs.
=> Add OSK and message box support to SDL2

.github/workflows/build.yml, index.html, make-repo-html.sh, package.html, style.css
This adds an index page and a page for each package with info on them to the github pages where we host the repository like mentioned in https://github.com/pspdev/psp-packages/issues/155. I used the scripts there as an example to build this. This is some very basic html, filled using environment variables and envsubst. You can see the result here: https://sharkwouter.github.io/psp-packages/
I also added an empty style.css file. So if someone feels like making this look better, then can get started immediately after this has been merged.
=> Add repo index pages

make-repo-html.sh
Currently the index lists dependencies, licenses and groups from the last package if the variable does not exist in the current one.
=> Unset lists which are not in every PSPBUILD

physfs/PSPBUILD, physfs/psp.patch
I'll take the initial port of physfs but the patch is credit to @stdgregwar 
- update to 3.2.0
this is the code i used to test
```c
-- snip the callback part --
int main(void)
{
SetupCallbacks();
pspDebugScreenInit();
const char *filename = "test.txt";
PHYSFS_init(NULL); // argv[0] is fine
PHYSFS_mount(".", NULL, 1);
PHYSFS_File *file = PHYSFS_openRead(filename);
PHYSFS_sint64 fileSize = PHYSFS_fileLength(file);
char *buffer = (char *)malloc(fileSize + 1);
size_t bytesRead = PHYSFS_readBytes(file, buffer, fileSize);
pspDebugScreenSetXY(0, 5);
while (!done)
{
//Null-terminate the buffer
buffer[bytesRead] = '\0';
//Print the file contents
pspDebugScreenPrintf("File contents: %s\n", buffer);
pspDebugScreenPrintf("Error: %s\n", PHYSFS_getErrorByCode(PHYSFS_getLastErrorCode()));
} …
```
=> add physfs package

tinygettext/PSPBUILD
This is a translation library with a zlib license that shares a lot with gnu gettext. For some reason it uses uncompiled translation files called .po files. It does work, though.
=> Add tinygettext

sdl2/PSPBUILD
This adds the following features for us:
- ShowMessageBox can be used without creating a window (thanks to @fjtrujy )
- Instead of forcefully closing the game, closing the game using the home button will throw and SDL_Quit event (that was me)
=> Upgrade SDL2 to version 2.30.7

physfs/PSPBUILD
This will make it be part of the prebuild toolchain. Currently users would have to manually install it to get it.
=> Add physfs to pspdev-default group

sdl2/PSPBUILD
There is a newer SDL2 version out now. I also made a PR today which adds locale support, allowing translations to work with the PSP, which I included in this PR as well.
=> sdl2: update to 2.30.9 and add locale support

sdl2/PSPBUILD
This also makes it a release build, which should speed up execution and make eboots smaller.
=> sdl2: update to version 2.30.10

angelscript/PSPBUILD, argtable2/PSPBUILD, bzip2/PSPBUILD, cjson/PSPBUILD, curl/PSPBUILD, enet/PSPBUILD, freetype2/PSPBUILD, harfbuzz/PSPBUILD, libmikmod/PSPBUILD, libmodplug/PSPBUILD, libogg/PSPBUILD, libpng/PSPBUILD, libpspvram/PSPBUILD, libvorbis/PSPBUILD, libxmp-lite/PSPBUILD, libxmp/PSPBUILD, libyaml/PSPBUILD, libzip/PSPBUILD, lz4/PSPBUILD, mini18n/PSPBUILD, minizip/PSPBUILD, physfs/PSPBUILD, sdl2-image/PSPBUILD, sdl2-mixer/PSPBUILD, sdl2-net/PSPBUILD, sdl2-ttf/PSPBUILD, squirrel/PSPBUILD, yaml-cpp/PSPBUILD, zlib/PSPBUILD, zziplib/PSPBUILD
This should speed up applications using these libraries and also lower  the size of both the libraries and the binaries that use them. We should make sure that all new libraries which are build using cmake build in release mode.
=> Build cmake based libraries in release mode

openal/PSPBUILD
This is an older port of OpenAL Soft from around 2009. The version of OpenAL in this repo (1.23.1) does not compile for the PSP. If anyone else wants to test this, I have an example program to test it with: https://github.com/illteteka/openal-soft-psp/tree/main/examples/pitch
=> Downgrade OpenAL Soft version to fix compatibility

libmodplug/PSPBUILD
It had full paths in it.
The sed in the CMakeLists.txt was needed because CMake was overwriting prefix, exec_prefix and libdir with full paths regardless of if they were in the file with @s around them otherwise.
=> Fix libmodplug.pc

mpg123/PSPBUILD
After 2 small changes, building and using libmpg123 for the PSP works again. I've tested it with SDL2_Mixer.
The patches used in building this package can be found in the following PRs upstream:
- https://github.com/madebr/mpg123/pull/17
- https://github.com/madebr/mpg123/pull/18
=> Add libmpg123

make-repo-html.sh, package.html
The link on the page of a package did not go directly to the package itself. This fixes that.
There are also some minor changes which made it work on my machine. Not setting the maxdepth makes the find command slower if you have build packages and can result in permission warnings. The default for GITHUB_REPOSITORY was just set wrong.
=> Link to package source directly

lua54/PSPBUILD
When trying to use lua.h in C, you'll constantly see issues type errors. This fixes this.
=> Fix lua54 long errors

mbedtls/PSPBUILD
The download url no longer goes anywhere useful, so I changed the PSPBUILD to use git and pull the commit that corresponds with the release we were already building. I also did some minor consistency fixes in the PSPBUILD.
=> Fix mbedtls build

mpg123/17.patch, mpg123/18.patch, mpg123/PSPBUILD
For some reason GitHub starts rate limiting if you download 2 patch files from PRs, so I added the 2 patches for mpg123 to the repo.
=> Fix 429 errors because of pulling too many patches

libpspmath/PSPBUILD
Straightforward addition of `libpspmath` to the pacman repo. I think originally there was some concern over licensing since the only living standalone repository doesn't bundle it, though MrMr[ICE] deliberately referenced the PSPSDK license header in `pspmath.h` and was a well-known figure head at the time (especially for the VFPU docs), so I don't think it's ambiguous to say its sharing the license with the PSPSDK as BSD 3-Clause.
=> Add libpspmath

build.sh
This prevents broken packages or conflicting packages from being built and installed
=> Implement BLACKLIST for LOCAL_PACKAGES

argtable2/PSPBUILD
I forgot about this one, but argtable2 wasn't building anymore. This small change fixes it for now.
=> Make argtable2 build with gcc 15.1.1

jsoncpp/PSPBUILD
Before this upgrade we were still building the object libs, which we don't actually need.
=> Upgrade jsoncpp to version 1.9.6

expat/PSPBUILD
The binaries are not generated due to -DEXPAT_BUILD_TOOLS=OFF, same for docs. It's better not to play with rm rf :)
=> Remove unnecessary rm commands
