pspdev/psp-packages

jsoncpp/PSPBUILD
jsoncpp/jsoncpp-1.8.4-PSP.patch

This is a simple library for reading and writing json in C++. I've been using it and it works well on the PSP.

Add jsoncpp library

---

angelscript/PSPBUILD
angelscript/angelscript_2.28.2.patch

The mips source file was not getting included.

Make angelscript able to build

---

libintrafont/PSPBUILD

This one comes from the pspdev/libintrafont repo. It seems to work okay on PPSSPP.

Add libintrafont

---

kubridge/PSPBUILD

It's a bit of a shame that I had to manually copy instead of using the install command, but it should work just fine.

Add kubridge

---

libconfuse/PSPBUILD

Now that https://github.com/pspdev/pspsdk/pull/73 is in, we can potentially just use this

Use upstream libconfuse

---

libmikmod/PSPBUILD

Additionally I made the license copy better and made libmikmod-config useful.

Fix libmikmod building a shared library

---

libpng/PSPBUILD

This makes the paths it spits out correct.

Fix libpng-config

---

libpspvram/PSPBUILD

This should fix the random build failures.

Update libpspvram to use cmake

---

sdl2/PSPBUILD

This release has all the recent changes. It's not that much different from what we packaged before.

Update SDL2 to 2.0.20 release

---

minizip/PSPBUILD

As requested by @wally4000. I haven't tested it, but it builds just fine.

Add minizip

---

opentri/PSPBUILD

Update references of OpenTRI in order to compile with the latest Binutils changes

Update openTRI hash

---

libdumb/PSPBUILD

EDIT: I did not use sed for the exec_prefix because it is the same value :)

fix pkgconfig libdumb

---

jsoncpp/PSPBUILD

They have the same value of `prefix` and `exec_prefix`

fix pkgconfig jsoncpp

---

curl/PSPBUILD

Is this the right line to put the sed commands?

fix pkgconfig curl

---

.github/workflows/build.yml

This is still WIP, but it's really needed.

Fix warnings

---

.github/workflows/build.yml
libzip/PSPBUILD

the latest libzip from https://libzip.org/

Add libzip 1.9.2

---

mbedtls/PSPBUILD
mbedtls/mbedtls-2.16.6-PSP.patch

This PR adds mbedTLS 2.16.6
- includes network patch to remove IPv6 requirement

Add mbedtls

---

libun7zip/PSPBUILD

ported a simple library to extract `.7z` files

Add un7zip library

---

libpspvram/PSPBUILD

(there's a commit and version mismatch)

Fix package version name

---

glm/PSPBUILD
libmodplug/PSPBUILD
lua51/PSPBUILD
lua51/psp.patch
mojoal/PSPBUILD
mojoal/psp.patch
physfs/PSPBUILD
physfs/psp.patch

PSP builds for several package needed by the solarus engine.
* libmodplug
* physfs
* lua51
* mojoal
* glm

[WIP] packages needed by solarus

---

yaml-cpp/PSPBUILD

I haven't tested using this library, but it builds just fine. The output looks good too. @humbertodias could you confirm if this works for you?
Closes #111

Add yaml-cpp

---

theora/PSPBUILD

I have not yet tested it, so this is more of request for comments, than a pull request.
Anything missing from my PSPBUILD? Anything that I am not doing right?

Add theora video decoding/encoding library

---

harfbuzz/PSPBUILD
harfbuzz/fix-cmake.patch

This fixes the build issues for mentioned in https://github.com/pspdev/pspdev.github.io/pull/35.

Add stdc++ to harfbuzz --libs in pkgconf

---

jpeg/PSPBUILD
libconfuse/PSPBUILD
zziplib/PSPBUILD

Fix jpeg / zziplib and libconfuse compilation issues.

GCC14 fixes

---

libpspexploit/PSPBUILD
sdl/PSPBUILD
theora/PSPBUILD

Update libpspexploit
Update Theora (LDFLAGS not in ./configure target)
Use fixed SDL1.2 commit

Further packages fixed for GCC 14

---

zlib/PSPBUILD

There seems to be some race condition, so lets make sure it uses only 1 job to build.

Fix zlib sometimes failing

---

pspla/PSPBUILD

[pspla](https://github.com/Jayanky/pspla) seems cool, packaging it

Add pspla library

---

enet/PSPBUILD

Also changed the link from github to project website and installing with `make install` now.

Bump enet library version

---

.github/workflows/build.yml

This makes it a lot more readable I would say, but does not change the functionality. This part of the code would only trigger for the master branch anyway.

Remove unused code in workflow

---

pspgl/PSPBUILD

Updating PSPGL reference after updating & merging both existing repos.
Thanks

Update PSPGL reference

---

xxhash/PSPBUILD

This is one of the packages mentioned in https://github.com/pspdev/pspdev/discussions/65; it's just nice to have. Both PPSSPP and PSP work. :D

Add xxhash package

---

sdl2/PSPBUILD
sdl3/PSPBUILD

New versions were just released.

Upgrade SDL2 and SDL3 to new versions

---

lua53/PSPBUILD

This one is a little bit different, but the same applies.

Fix long in lua 53

---

libpspexploit/PSPBUILD

Just update to have a proper source instead of just commit, thanks.

Update libpspexploit package

---

sdl3/PSPBUILD

It is a small bugfix update and should work without issue.

SDL3: Update to 3.2.4

---

index.html

This should make the page more useful and improve our search engine optimization.

Add additional info to the index page

---

liblzma/PSPBUILD

add fix to liblzma, removes call to `sysconf()`

Fix lzma library
